### PR TITLE
Fixing error when editing chat posts with editable reblogs enabled

### LINKED ISSUE #515: Chat post gives "Invalid Editor Type"
http://prntscr.com/8hseig
This is the user's gist: https://gist.github.com/anonymous/c325144bd42e17ddedc2
Already went through most of our common trouble shooting, couldn't track down the issue. Can't reproduce locally either
It only seems to happen on creating or reblogging a chat post though

### LINKED ISSUE #538: Editable Reblogs Error Message on New Chat Post
When creating a NEW chat post, the following error message pops up.  And it only occurs for the chat type, all other types function correctly.  Also my editor is already set to rich text.

screen shot 2015-09-25 at 12 17 38 am

### PR DESCRIPTION
**Pull request by blackjackkent**
Resolves #515 
Resolves #538

### CODE REVIEW

File: Extensions/xkit_patches.js [hunk 1]
```diff
@@ -662,12 +662,16 @@ XKit.tools.dump_config = function(){
...
 				get_content_html: function() {
 					if ($(".html-field").css("display") === "none") {
+						//rich text editor
 						var content_editor = $('.post-form--form').find('.editor.editor-richtext');
 						if (content_editor.length === 0) {
 							console.error('ERROR: unable to get content html');
 							return '';
 						}
 						return content_editor.html();
+					} else if ($('.chat-field').css("display") != "none") {
```
Comment (Wolvan) [inline Extensions/xkit_patches.js]: use ``!==`` for comparison, please

Comment (blackjackkent) [inline Extensions/xkit_patches.js]: Weird that Travis didn't yell about that. O.o Anyway, updated.

**Comment by finagle29** [comment]
LGTM, @homu r+
