### PR TITLE
Fix various extension options (unneeded, typos, improper labelling)

### LINKED ISSUE #247: Remove deprecated features from UserMenus+
From an ask:

> User Menus + 2.5.3 (Chrome) has a deprecated feature: "Enable sending anonymous messages from the dashboard." This is enabled even without the extension via tumblr default interface.

I have a feeling more than that is deprecated.

### PR DESCRIPTION
**Pull request by AprilSylph**
Removes:
- Hermes' unneeded options header
- "Anonymous asks from the dashboard" (very old; now vanilla tumblr), resolves #247 
- Photo replies auto-enabling in tweaks (remember photo replies?)
- Hide Find Blogs button tweak (such a button no longer exists)

Fixes a few typos and makes AlreadyReblogged's "what is this?" button look nicer

Properly labels anything marked as "(might slow down your computer)" or "(experimental)" (now uses the proper icon)

### CODE REVIEW

File: Extensions/show_more.js [hunk 1]
```diff
@@ -660,48 +651,6 @@ XKit.extensions.show_more = new Object({
 
 		}
 
-		if (XKit.extensions.show_more.preferences.enable_anon.value) {
```
Comment (hobinjk) [inline Extensions/show_more.js]: This is now a feature in vanilla tumblr, right?

Comment (AprilSylph) [reply Extensions/show_more.js]: yep, i think this is a long leftover option for a feature that xkit doesn't even have anymore

Comment (AprilSylph) [reply Extensions/show_more.js]: yeah, even with xkit's classic user menu the vanilla askbox gets pulled up, which has an anonymous toggle
