### PR TITLE
Resolve #1205

### LINKED ISSUE #1205: Editing posts with ER is broken
very recent regression

1. reblog a post to your drafts, trim some content
2. go to your drafts
3. click "edit"
4. click "save".
5. notice that the saved version doesn't have the `<xkit>` tags, and thus is broken.

not sure how much of this is required, but its definitely a problem with not handling edits correctly

### PR DESCRIPTION
**Pull request by blackjackkent**
Wraps all links in a `<span>` prior to posting (whether or not the reblog tree has been processed); has zero impact on the post as displayed but also circumvents the user link header being processed as a malformed reblog.

### CODE REVIEW

File: Extensions/editable_reblogs.js [hunk 1]
```diff
@@ -341,6 +346,7 @@ XKit.extensions.editable_reblogs = new Object({
 
 	make_post: function(e) {
 		if (!this.reblog_tree_exists() || this.state != "success") {
+			XKit.interface.post_window.set_content_html(this.wrap_html_links(XKit.interface.post_window.get_content_html()));
```
Comment (nightpool) [inline Extensions/editable_reblogs.js]: This feels like a race condition—how do we know whether our event handler or tumblr's event handler will be called first?

Comment (blackjackkent) [inline Extensions/editable_reblogs.js]: Good catch. :O There's at least one edge case that needs this to fire on submit rather than load, so I updated it to always remove the handler attribute and then re-add/fire it on form submit if the reblog tree hasn't been processed.

**Comment by nightpool** [comment]
Works for me, solves the current problem and i've tested it. I don't know if its a great long term solution though, because the `span`s still don't persist between edits. Needs a version bump.

**Comment by nightpool** [comment]
@homu d+

**Comment by nightpool** [comment]
@homu delegate+

**Comment by nightpool** [comment]
Gonna hold off on this today b/c of the big ER issue we just ran into

**Comment by nightpool** [comment]
Okay, 3, 2, 1...
Let's jam
@homu r+

**Comment by Wolvan** [comment]
See you, space cowboy
