### PR TITLE
[Read More Now] Use peepr API

### LINKED ISSUE #177: Read More Now doesn't handle previous replies correctly
> Hi! I couldn't see this on the 'broken shit' section, apologies if it's there! When reblogging a reply that's been hidden under a 'Keep Reading/Read More', the previous reply disappears in the reblog screen and I'm having to paste the last reply in before I do my own. I think this happens pretty much every time if the last reply has been hidden under a cut.

### LINKED ISSUE #185: Issue with multiple "Keep reading" links
I noticed something after I reblogged a post with a "Keep reading" cut and put my response in the "Keep reading" link too.

This happens if you click the second Read More Now! button first.
readmore1
The first Read More Now! button just disappears.

This happens if you click the first Read More Now! button first.
readmore2
Clicking on the first button works fine, but when you click on the second it seems like you haven't clicked on the first one at all. And the first Read More Now! button disappears like in the first case.

I think it would be nice to make it possible to read what's under each "Keep reading" link at the same time on the dashboard. Make it so what's already retrieved by the first button doesn't disappear after clicking on the second one. And if you start with clicking on the second one, make it so the first button itself doesn't disappear.

Maybe the extension needs to count how many "Keep reading" links there are in a post?

### LINKED ISSUE #537: Read More Now not working outside of Dashboard
I've mentioned this in another Read More thread, but I've been advised to open a new issue:
When being on drafts, private mode or queues etc., opening the Read More Now link does not work and only re-directs me to the blog with the read more (which is the basic tumblr feature without XKit).

Though, I'd like to add, that using drafts is something necessary for RPers. Therefore it'd be nice to make it work for anything outside the tumblr dashboard.

### LINKED ISSUE #556: Read More doesn't use new Tumblr layout
Part of testing #360.
initial
Click the lower one, expect to see only the lower one's content in its place:
click one
For contrast, this is what the upper one looks like after clicking:
click two

In other news, the way staff implemented the update appears to be Special

### LINKED ISSUE #908: "Read More Now" not loading the post it's attached to
When I click "Read More Now" at the bottom of a post, it loads text from a different post on my dash, seemingly the first few lines of the most recent post by that original post author. If the post I'm trying to expand is already the author's most recent, the text that comes up is "undefined."

### LINKED ISSUE #1217: Read More Now breaks on custom "Keep reading" links
Opening [this post](http://norcumi.tumblr.com/post/153460768694/photographer-endangers-his-life-to-capture-lava) on the dashboard creates a Read More Now button, even though the "Keep reading" link goes off-site. Clicking the button replaces the post with another entirely unrelated post. The button should be hidden in these scenarios in order to ensure nothing breaks.

### PR DESCRIPTION
**Pull request by AprilSylph**
Rewrite of Read More Now to use the peepr API. ~~The UI has been updated to integrate the extension with the dashboard more, visually turning the default "Keep Reading" centered links into dropdown buttons.~~

- ~~Readmores are now fetched automatically rather than on click for a more seamless experience~~
  - Posts are now cached in the current session
- Grabs only the relevant post/reblog from the readmore link
  - resolves #177
  - resolves #185 
  - replaces & closes #360
  - resolves #556
  - resolves #908 
- Removes public blog/post restriction
  - allows readmores on dash-only blogs to be read
  - resolves #537 
- Properly parses custom domain "Keep Reading" reblog links, doesn't activate for off-site links
  - resolves #1217
- ~~The extension is now completely language-neutral!~~

### CODE REVIEW

File: Extensions/read_more_now.js [hunk 1]
```diff
@@ -1,211 +1,104 @@
...
-				json: true,
-				onerror: function() {
-					$(m_cont).removeClass("disabled");
-					$(m_cont).html(XKit.extensions.read_more_now.button_caption);
-					XKit.extensions.read_more_now.show_failed();
-				},
-				onload: function(response) {
-					var data = JSON.parse(response.responseText);
-					var m_object = data.response;
+	find_links: function() {
```
Comment (nightpool) [inline Extensions/read_more_now.js]: the fact that the function named `find_links` is also responsible for 1) fetching the posts and 2) adding those contents to the links is kind of confusing for me. I'm also not completely happy with the idea of fetching every read more post into a details element immediately—can't we do it lazily when you click to reveal it?

File: Extensions/read_more_now.js [hunk 2]
```diff
@@ -1,211 +1,104 @@
...
-					} else {
-						// If url is not of the form
-						// http://something.tumblr.com/post/numbers/whatever it needs to be
-						// determined based on the post's author
-						var real_prefix = 'https://' + post.attr('data-tumblelog-name') + '.tumblr.com/';
-						var real_link = link.attr('href').replace(/https?:\/\/[^\/]+\//, real_prefix);
-						XKit.extensions.read_more_now.append_button_with_link(link.parent(), real_link);
-					}
+					let comment = responseData.posts[0].reblog.comment;
+					let readmore = comment.substring(comment.indexOf("[[MORE]]") + 8).replace(/\[\[MORE\]\]/g, "");
```
Comment (nightpool) [inline Extensions/read_more_now.js]: why do both? shouldn't we just substring? if someone includes the [[MORE]] twice, that isn't really our problem, right?

File: Extensions/read_more_now.js [hunk 3]
```diff
@@ -1,211 +1,104 @@
...
-		var div = document.createElement("div");
-		div.classList.add("xkit-read-more-now");
-		div.classList.add("xkit-button");
-		div.dataset.postUrl = url;
-		div.innerHTML = XKit.extensions.read_more_now.button_caption;
-		if (XKit.extensions.read_more_now.preferences.inline_button.value === true) {
-			div.setAttribute("style", "display: inline-block; text-align: center; margin-left: 10px; margin-top: 0; float: right;");
+	get_username: url => {
+		if (url.includes(".tumblr.com") || !url.includes(".")) {
+			return new Promise(resolve => resolve(url.split(".")[0]));
```
Comment (nightpool) [inline Extensions/read_more_now.js]: `Promise.resolve(url.split(".")[0])`

Comment (nightpool) [reply Extensions/read_more_now.js]: also `let [username] = url.split(".")`

File: Extensions/read_more_now.js [hunk 4]
```diff
@@ -1,211 +1,104 @@
...
+		$("a.tmblr-truncated-link:not(.xreadmore-done)")
+		.addClass("xreadmore-done")
+		.each(function() {
+			const $link = $(this);
+			const href = $link.attr("href");
+			let url;
+			let postID;
+
+			if (!href.includes("t.umblr.com")) {
+				let link_parts = href.split("://")[1].split("/");
```
Comment (nightpool) [inline Extensions/read_more_now.js]: `let [url, _, postID] = `

Comment (nightpool) [reply Extensions/read_more_now.js]: or we could do this with a regex match and named capture groups.

File: Extensions/read_more_now.js [hunk 5]
```diff
@@ -1,211 +1,104 @@
 //* TITLE Read More Now **//
-//* VERSION 1.4.7 **//
+//* VERSION 2.0.0 **//
 //* DESCRIPTION Read Mores in your dash **//
-//* DETAILS This extension allows you to read 'Read More' posts without leaving your dash. Just click on the 'Read More Now!' button on posts and XKit will automatically load and display the post on your dashboard. **//
-//* DEVELOPER STUDIOXENIX **//
+//* DETAILS This extension changes &quot;Keep Reading&quot; links into collapsible elements for easy viewing. **//
```
Comment (nightpool) [inline Extensions/read_more_now.js]: I'm not 100% confident on the details element change as a UI change—I don't want to break people's assumptions about how XKit's interface works or make them think Read More Now has stopped working. Also, under the old design you could choose whether to click the keep reading link or the read more now button, which you can't with the new extension.

File: Extensions/read_more_now.js (hunk 1 above)
Comment (AprilSylph) [reply Extensions/read_more_now.js]: i know the intention of this comment was to just have me rename the function, but it made me realise i could give the rest of the contained code an extension object `this` by calling a different extension function within the `.each`, so i hope you don't mind `process_link` as the name of the do-everything function ^_^;

as for the fetching everything immediately part, that'll be resolved when i address your last comment, where I'll revert the UI change and with it the fetch time

File: Extensions/read_more_now.js (hunk 5 above)
Comment (AprilSylph) [reply Extensions/read_more_now.js]: i have to admit i have a personal bias towards integrating XKit with Tumblr's interface more closely but you're completely right. I'll change the UI and fetch time back to how it used to work

File: Extensions/read_more_now.js [hunk 6]
```diff
@@ -1,211 +1,121 @@
...
-			if (post.hasClass("xread-more-now-done")) {
-				return;
-			}
-			post.addClass("xread-more-now-done");
-
-			if (post.hasClass("read_more_container")) {
-				XKit.extensions.read_more_now.handle_read_more_post(post);
-				need_reflow = true;
+		if (!href.includes("t.umblr.com")) {
+			[url,, postID] = href.split("://")[1].split("/");
```
Comment (hobinjk) [inline Extensions/read_more_now.js]: I'm guessing this isn't a typo but adding a `_` to the middle would make your intent clearer

File: Extensions/read_more_now.js [hunk 7]
```diff
@@ -1,211 +1,121 @@
...
-		if (need_reflow) {
-			XKit.interface.trigger_reflow();
+	get_username: url => {
+		if (url.includes(".tumblr.com") || !url.includes(".")) {
+			let [username] = url.split(".");
+			return Promise.resolve(username);
+		} else {
+			return fetch(`https://www.tumblr.com/api/v2/blog/${url}/info?api_key=${XKit.api_key}`)
+				.then(response => response.json())
+					.then(responseData => responseData.response.blog.name);
```
Comment (hobinjk) [inline Extensions/read_more_now.js]: nit: these would look nicer aligned

File: Extensions/read_more_now.js (hunk 6 above)
Comment (AprilSylph) [reply Extensions/read_more_now.js]: i thought this was less ugly than either using `__` or taking another line to `let _;` since just adding `_` here overwrites the entirety of lodash lol

happy to change it, the question is to which option

Comment (hobinjk) [reply Extensions/read_more_now.js]: Riiiight, of course this isn't straightforward. Maybe `[url, /* discard */, postId]`? I just want something since my keyboard occasionally doubles the`,` key and this looks exactly like that

Comment (AprilSylph) [reply Extensions/read_more_now.js]: ooooh yeah, that's good
