### PR TITLE
Outbox: fixes no messages being saved when sent from dash or inbox

### LINKED ISSUE #783: Outbox: Not saving messages
Hello!! I've been experiencing this issue I think for about a month now? My outbox isn't saving all of my messages. It was being problematic and with some help from one of your team I was able to see that this issue occurs when I'm on my Tumblr dash initiating an inbox message it won't save. If I'm on someone's blog (ie url.tumblr.com/ask) it saves, but clicking on their ask icon within the dash, or the little bubble icon when I'm in my inbox to initiate a "new" as from a response, it's not saved. This makes my rainbows sad.

### PR DESCRIPTION
**Pull request by izub**
Fixes #783 & #699

### CODE REVIEW

File: Extensions/outbox.js [hunk 1]
```diff
@@ -177,7 +177,9 @@ XKit.extensions.outbox = new Object({
 
 		var form_key = XKit.interface.form_key();
 
-		$(document).on("click", "#ask_button", function() {
+		$(document).on("click", ".post-form--asks .ask-button", function() {
+
+			var $form = $(this).closest('form');
```
Comment (nightpool) [inline Extensions/outbox.js]: why `.closest(form)` over `.parent`?

File: Extensions/outbox.js [hunk 2]
```diff
@@ -196,19 +198,15 @@ XKit.extensions.outbox = new Object({
...
 			}
 
-			m_username = document.location.href.substring(document.location.href.indexOf('/ask_form') + 10);
-			m_username = m_username.substring(0, m_username.indexOf("."));
-
 			var m_obj = {};
 			m_obj.avatar = "ask";
-			m_obj.username = $("#from").find(".tumblelog_name").html();
-			m_obj.message = $("#question").val();
+			m_obj.username = $form.find('.ask-from span:visible').text();
```
Comment (nightpool) [inline Extensions/outbox.js]: changes behavior—will record "anonymous" for anonymously sent messages, rather then the old behavior, which always records the blog username.

File: Extensions/outbox.js [hunk 3]
```diff
@@ -196,19 +198,15 @@ XKit.extensions.outbox = new Object({
...
+			m_obj.message = $form.find('textarea[name=question]').val();
 			m_obj.answer = "";
-			m_obj.to = $("#recipient_label").html();
+			m_obj.to = $form.find(".ask-recipient-label").html();
```
Comment (nightpool) [inline Extensions/outbox.js]: why .html instead of .text like above?

File: Extensions/outbox.js (hunk 1 above)
Comment (izub) [inline Extensions/outbox.js]: .closest() will travel up the DOM tree from the element until it finds the selector, while .parent only travels up one level. This requires you to do parent().parent().parent() etc. which makes it easy to break after tumblr changes something. And .parents() is less efficient than .closest().

File: Extensions/outbox.js (hunk 2 above)
Comment (izub) [inline Extensions/outbox.js]: This is true. However the username is actually never used in the outbox. Regardless, I think this is the proper behavior. If we ever want to distinguish between public and anonymous messages in the outbox.

File: Extensions/outbox.js (hunk 1 above)
Comment (nightpool) [inline Extensions/outbox.js]: right, but parent("form") will break immediately if something changes, while closest("form") may or may not return the same element we're expecting it to.

anyway, we don't need the form to find the elements we want. just use a $this variable instead.

File: Extensions/outbox.js (hunk 2 above)
Comment (nightpool) [inline Extensions/outbox.js]: the username is used when rendering asks on 490. putting "anonymous" here will break it.

File: Extensions/outbox.js (hunk 1 above)
Comment (izub) [inline Extensions/outbox.js]: I'd rather write something that is more flexible to tumblr changes. But I do agree the selector could be more specific to make sure it will always return either the correct element or nothing.

File: Extensions/outbox.js (hunk 2 above)
Comment (izub) [inline Extensions/outbox.js]: If you're referring to the lines 
https://github.com/new-xkit/XKit/blob/7bd8bffe375c940dea3de5a2dce4e204ee948a3e/Extensions/outbox.js#L492-L493
These lines are unused.

File: Extensions/outbox.js (hunk 1 above)
Comment (izub) [inline Extensions/outbox.js]: $(this) would refer to the button, or did you mean something else with $this?

Comment (nightpool) [inline Extensions/outbox.js]: oops sorry, I meant the ".post-form--asks" selector. minor brainfart.

File: Extensions/outbox.js (hunk 2 above)
Comment (nightpool) [inline Extensions/outbox.js]: why do you think they're unused? They're obviously used...

File: Extensions/outbox.js (hunk 1 above)
Comment (izub) [inline Extensions/outbox.js]: That seems fair!

File: Extensions/outbox.js (hunk 2 above)
Comment (nightpool) [inline Extensions/outbox.js]: Fair enough, but we should still record the user sending the message. If you want to introduce a new feature that allows you to see whether you sent it anonymously or not, that should be a different field.

**Comment by nightpool** [comment]
Thanks! This looks great. 

super happy to see some new faces around here :D If you haven't already, come join us in [our gitter channel!](https://gitter.im/new-xkit/XKit)

@homu r+
