### PR TITLE
Fix showing Welcome bubble anywhere but on the dashboard

### LINKED ISSUE #590: Welcome/tour not dismissable on pages other than Dash
Got this one from a friend.

Rough steps to reproduce:
1. Do a fresh install of XKit
2. Log out of Tumblr
3. Visit a blog permalink (do this before logging in or visiting the Dashboard)
4. Notice the XKit welcome message that isn't in any way dismissable (see below)

e08bff31f579faa8892b25ee3e44eb1e564de8421162fc4590 pimgpsh_fullsize_distr

In order to dismiss the welcome message, you have to log in and click on the XKit icon in Tumblr's menubar; there doesn't seem to be any other way to dismiss the message.

### PR DESCRIPTION
**Pull request by Wolvan**
Fixes #590

### CODE REVIEW

File: Extensions/xkit_preferences.js [hunk 1]
```diff
@@ -107,7 +107,7 @@ XKit.extensions.xkit_preferences = new Object({
 
 		//$("#new-xkit-control").tipTip({maxWidth: "auto", edgeOffset: 0, delay: 10 });
 
-		if(XKit.storage.get("xkit_preferences", "shown_welcome_bubble") !== "true") {
+		if(XKit.storage.get("xkit_preferences", "shown_welcome_bubble") !== "true" && XKit.interface.where().dashboard) {
 			XKit.extensions.xkit_preferences.show_welcome_bubble();
```
Comment (dlmarquis) [inline Extensions/xkit_preferences.js]: I think we're styling these as ![blah] instead of using !==.

Comment (ThePsionic) [inline Extensions/xkit_preferences.js]: Except the storage doesn't store anything but strings at the moment, so we have to compare specifically against a string rather than a boolean. Until #548 is pulled, this is the way to do it - after it has been pulled we'll need a massive cleanup of code, too.

Comment (Wolvan) [inline Extensions/xkit_preferences.js]: That doesn't work if it's a string that gets returned. For a boolean you would be right

Comment (dlmarquis) [inline Extensions/xkit_preferences.js]: Right. I didn't see that, despite noticing that !== True was a weird-ass construction. LGTM, then.

**Comment by dlmarquis** [comment]
Did something change so that homu can automerge mismatched versions? I was expecting it to say something when I pushed your other PR.

**Comment by Wolvan** [comment]
No idea, it complained on my other PR for preferences

**Comment by dlmarquis** [comment]
You should probably bump this one just in case? Or I could try to push anyway and see what happens .

**Comment by Wolvan** [comment]
Current version is 5.1.1, bumped version is 5.1.1 and we haven't rebuilt the extension dist, so nobody got the 5.1.1 update yet. I think you're good

**Comment by finagle29** [comment]
@dlmarquis said the magic word LGTM
@homu r=dlmarquis
