### PR TITLE
fix keyboard shortcuts in OCP

### LINKED ISSUE #1577: Keyboard shortcut to reblog or quickqueue with One Click Postage does not complete action on Firefox
Keyboard shortcut to reblog or quickqueue with One Click Postage does not complete action on Firefox. UI element continues spinning without timeout or error code generated. One Click Postage using mouse on UI to reblog or quickqueue still works properly, so this is something distinct to the keyboard shortcut and different than previous bug where One Click produces error code. 

screen shot 2018-06-16 at 10 17 30 am

This is new behavior within last 12 hours, and I've reproduced across two accounts on two different systems, one mac and one linux. Also attempted disabling and re-enabling One Click and the keyboard shortcut features. Finally, confirmed issue persists with all other extensions disabled.

### PR DESCRIPTION
**Pull request by AprilSylph**
resolves #1577 - the problem was that calling `Tumblr.KeyCommands.resume()` (since it is temporarily suspended to process OCP's shortcuts instead) was resetting `add_tag`, meaning Nx_XHR's data was wiped before it was finished. This makes Nx_XHR tamper-proof by saving its data to a separate/local variable as soon as it's opened.

### CODE REVIEW

File: Extensions/xkit_patches.js [hunk 1]
```diff
@@ -138,7 +138,70 @@ XKit.extensions.xkit_patches = new Object({
 	},
 
 	patches: {
-		"7.9.0": function() {},
+		"7.9.0": function() {
+			XKit.tools.Nx_XHR = function(details) {
```
Comment (hobinjk) [inline Extensions/xkit_patches.js]: Shouldn't this still be in 7.8.2 since the current distributed version is 7.8.2?

Comment (AprilSylph) [reply Extensions/xkit_patches.js]: putting it in 7.9.0's patches is just the lazy way, means I don't have to put it into xkit.js (yet). also i just noticed i forgot the version bump whoops

Comment (hobinjk) [reply Extensions/xkit_patches.js]: :+1:
