### PR TITLE
Editable reblogs fixes

### LINKED ISSUE #434: Read Mores misbehaving with Editable Reblogs
It appears there's a bug where when reblogging, Read Mores delete what's under them and just show up as [[MORE]]. It appears to only happen when Editable Reblogs are active. Multiple people have experienced this.

### PR DESCRIPTION
**Pull request by blackjackkent**
Fixes #434 #436 #437

### CODE REVIEW

**Comment by nightpool** [comment]
title text looks weird:
image

**Comment by nightpool** [comment]
reblogging posts without text content duplicates blockquotes and reblog_list

File: Extensions/editable_reblogs.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ XKit.extensions.editable_reblogs = new Object({
 		this.running = true;
 
 		XKit.interface.post_window_listener.add("editable_reblogs", XKit.extensions.editable_reblogs.post_window);
-		XKit.tools.add_css(".control-reblog-tree {display: none; }", "editable_reblogs_remove_content_tree");
+		XKit.tools.add_css(".control-reblog-tree {display: none; } .post-form--header .reblog-title {margin: 10px;} .", "editable_reblogs_remove_content_tree");
```
Comment (nightpool) [inline Extensions/editable_reblogs.js]: stray period?

**Comment by nightpool** [comment]
looks great! 
@homu r+
