### PR TITLE
fix logic on when to add CSS to hide reblogs

### LINKED ISSUE #351: Show originals appears not to work
Via the [support Gitter](https://gitter.im/new-xkit/support):

> \<XKit|86653\> Hey. Thanks for reviving this extension  I was wondering if you knew that show originals appears not to work. This is with all other xkit extensions disabled. I've tried in the latest version of Chrome but not Firefox.
> \<XKit|86653\> It doesn't appear to be in the github issue log.
> \<XKit|86653\> Show originals does still work with the old version of Xkit though.

### PR DESCRIPTION
**Pull request by finagle29**
fixes #351

### CODE REVIEW

**Comment by hobinjk** [comment]
Needs a version bump

File: Extensions/show_originals.js [hunk 1]
```diff
@@ -111,11 +111,8 @@ XKit.extensions.show_originals = new Object({
 			return;
 		}
 
-		// This probably doesn't ever happen
-		if (!XKit.extensions.show_originals) {
-			XKit.extensions.show_originals.added_css = true;
-			XKit.tools.add_css(" .post.is_reblog { display: none; ", "show_originals_on");
-		}
+		XKit.extensions.show_originals.added_css = true;
+		XKit.tools.add_css(" .post.is_reblog { display: none; ", "show_originals_on");
```
Comment (hobinjk) [inline Extensions/show_originals.js]: This looks like it doesn't have the closing brace like `.post.is_reblog { display: none; }`

**Comment by hobinjk** [comment]
LGTM
@homu r+
