### PR TITLE
ReplyViewer: restore links to commenters posts

### LINKED ISSUE #402: Allow View Comments to see when pictures are added
Right now, when someone reblogs a post with <em>only</em> a picture or gif, View Comments can't see that there's been content added and just skips over it. It'd be great if there was a way to see that a picture has been added, even if it's only a tag of [picture] instead of the whole photo.

### LINKED ISSUE #1118: reply viewer doesn't link to blogs correctly
> Hi, I wanted to tell y'all about something (you might already know?). ReplyViewer appears to be broken. I used to be able to click on peoples' names and get taken to where they'd reblogged the post, but now if I click it i just get taken to an "undefined" page. This isn't a critical bug since I can work around it by clicking Notes (which now helpfully works much the same way), but i'm still used to clicking on TagViewer and then ReplyViewer, and it's sad to see one of them broken.

### PR DESCRIPTION
**Pull request by wastingyourgum**
Fixed Issue #1118 using /svc/notes API as used in tagviewer. For reblogs will grab added text from notes if present but check post directly if not. Returned comment (if there is one) is in HTML so some stripping required. Bonus: shows you if a reply consisted of just an image (e.g. a gif) which notes and previous replyviewer don't.

---

resolves #1118, resolves #402

### CODE REVIEW

File: Extensions/replyviewer.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ XKit.extensions.replyviewer = new Object({
 
 	running: false,
 	slow: false,
-	apiKey: XKit.api_key,
+	apiKey: "5CIOyjHfcrNFlyEJl2D7vnoDTYqV30lNAUaSd4LJKoBFOZOmxp",
```
Comment (AprilSylph) [inline Extensions/replyviewer.js]: our API key is fine

File: Extensions/replyviewer.js [hunk 2]
```diff
@@ -114,37 +95,85 @@ XKit.extensions.replyviewer = new Object({
...
+												XKit.extensions.replyviewer.found_count++;
+											}
+										}
+									}
+
+								} catch (e) {
+									console.error("replyviewer -> Can't parse JSON at " + api_url + " -> " + e.message);
+								}
+							}
+						})
```
Comment (AprilSylph) [inline Extensions/replyviewer.js]: linter says missing semicolon

File: Extensions/replyviewer.js [hunk 3]
```diff
@@ -210,7 +225,7 @@ XKit.extensions.replyviewer = new Object({
 			}
 
 		});
-
+
```
Comment (AprilSylph) [inline Extensions/replyviewer.js]: unneeded whitespace
