### PR TITLE
Fix issues with Glowing Follow

### LINKED ISSUE #844: Glowing Follow doesn't work properly
Hi guys, i was reviewing this extension and some blogs not glow button. 
why is this happening? could be much brighter this button in some blogs you can not see very well or at least choose the color we want to glow.

screenshot_51
screenshot_52

PS: Excuse my English, I speak Spanish but I try to help.

### PR DESCRIPTION
**Pull request by hobinjk**
Improves Glowing Follow's short description. Fixes iframe URL detection
for Tumblr update. Updates class used for follow button detection.

Fixes #844.

### CODE REVIEW

File: Extensions/glowing_follow.js [hunk 1]
```diff
@@ -14,10 +14,10 @@ XKit.extensions.glowing_follow = new Object({
 		this.running = true;
 		XKit.tools.init_css("glowing_follow");
 
-		if ($(".follow").length > 0) {
+		var follow_button = $(".follow-button");
```
Comment (nightpool) [inline Extensions/glowing_follow.js]: Would prefer this to be a new XKit.iframe function. (because I think some blogs still might not have the new controls)

Comment (nightpool) [inline Extensions/glowing_follow.js]: the selector would be `.btn.follow,.tx-button.follow-button` then

Comment (hobinjk) [inline Extensions/glowing_follow.js]: Good catch, fixed.

**Comment by nightpool** [comment]
doesn't work on blogs with dark backgrounds because it's just varying the opacity. mind filing a followup issue?

@homu r+

**Comment by hobinjk** [comment]
@nightpool I filed #886 as a follow-up.
