### PR TITLE
Fixing logic that was causing only last servant condition to be evaluated

### LINKED ISSUE #459: Servant logic ignores all but last condition
Steps to repro:
1. make new servant with multiple conditions (e.g. post type is, post is from, post is original, etc.)
2. observe that the action is performed only when the last condition is met

### PR DESCRIPTION
**Pull request by blackjackkent**
Fixes #459

### CODE REVIEW

File: Extensions/servant.js [hunk 1]
```diff
@@ -1338,7 +1338,7 @@ XKit.extensions.servant = new Object({
 
 			// alert("on " + obj.id + ":\n" + "returned " + m_result.run + " on causer " + i + " --- parameter = " + cause.value + "\ntype = " + cause.id);
 
-			if (m_result.run === false) {
+			if (m_result.run === false || do_run == 0) {
```
Comment (Wolvan) [inline Extensions/servant.js]: Use === as travis says

**Comment by blackjackkent** [comment]
Updated. :O

**Comment by ThePsionic** [comment]
Tested, works beautifully.
@homu r+
