### PR TITLE
Fix sending asks when classic menu is enabled

### LINKED ISSUE #42: Sending asks from dashboard with User Menus+ fails

### PR DESCRIPTION
**Pull request by bvtsang**
Plus some refactoring.

Fixes #42.

The `Tumblr.DashboardAsk.open_ask` function I'm trying to call looks like:

```javascript
function(g) {
    Tumblr.Popover.hide_all();
    var h = g.attr("data-tumblelog-name");
    var i = (parseInt(g.data("anonymous-ask"), 10) === 1) ? true : false;
    this.model = new f();
    if (this.view) {
        this.view.destroy()
    }
    this.view = new b({
        model: this.model,
        recipient: h,
        allow_anonymous: i
    }).show_form()
}
```

### CODE REVIEW

File: Extensions/show_more.js [hunk 1]
```diff
@@ -869,6 +839,20 @@ XKit.extensions.show_more = new Object({
 
 	},
 
+	intercept_classic_menu_ask: function(event) {
+		event.preventDefault();
+
+		XKit.tools.add_function(function(){
+			var args = JSON.parse(add_tag);
+			var config = jQuery("<div data-tumblelog-name='" + args.recipient + "' />");
+			config.data("anonymous_ask", args.anonymous_asks);
```
Comment (blackjackkent) [inline Extensions/show_more.js]: Is this config item supposed to add an "Ask as anonymous" control? My recipient blog definitely supports anonymous asks but I am not seeing such a control:

anon

File: Extensions/show_more.js [hunk 2]
```diff
@@ -645,8 +618,8 @@ XKit.extensions.show_more = new Object({
 
 				var username = $(this).parent().attr('data-tumblelog-name');
 
-				if (XKit.extensions.show_more.submit_available[username] === true ||
-					XKit.extensions.show_more.submit_available[username] === false) {
+				if (XKit.extensions.show_more.submit_available[username] ||
+					!XKit.extensions.show_more.submit_available[username]) {
```
Comment (coderpatsy) [inline Extensions/show_more.js]: Won't this always return? This question applies to likes_available and anon_available below.

Before this change it would only return if the properties were booleans, but I haven't looked into whether they could be anything else.

Comment (bvtsang) [inline Extensions/show_more.js]: Good catch. To be safe, I'll change them to `if (typeof(XKit.extensions.show_more.submit_available[username]) === "boolean")` as well as elsewhere in this file.

**Comment by bvtsang** [comment]
I've made the if statements check if the values are booleans and sacrificed the appropriate materials to Travis CI.

**Comment by blackjackkent** [comment]
TRAVIS IS APPEASED. THE RITUAL MAY PROCEED.

@homu r+
