### PR TITLE
Fixing style of blogtracker links on Following page

### LINKED ISSUE #288: track blog tumblr is broken on the /following page
image
mousing over it:
image

### PR DESCRIPTION
**Pull request by blackjackkent**
Fixes #288

### CODE REVIEW

**Comment by bvtsang** [comment]
Nitpick: missing newlines at end of files

File: Extensions/people_notifier.js [hunk 1]
```diff
@@ -311,13 +311,16 @@ XKit.extensions.people_notifier = new Object({
 		} else {
 
 			var current_ms = new Date().getTime();
-
+			var text_color = "rgba(255, 255, 255, 0.5)";
+			if ($('body').hasClass('dashboard_useraction_following')) {
```
Comment (bvtsang) [inline Extensions/people_notifier.js]: If we just wanted to check if we were on the `/following` page, I think it would be better to add a field for that in `XKit.interface.where()`.

**Comment by blackjackkent** [comment]
Whoops, updated. Also made a fix to appease Travis cos I was a bad girl and didn't lint before pushing. :P

**Comment by bvtsang** [comment]
Don't forget to bump up the version of xkit_patches.

**Comment by bvtsang** [comment]
LGTM

@homu r+
