### PR TITLE
Fix timestamps in search view

### LINKED ISSUE #1342: Timestamps broken in search view
Timestamps extension looks for permalink using:

`if (post.find('.permalink').length <= 0 && post.find(".post_permalink").length <= 0)`

and aborts if not found. This always fails on search.

In quick testing, this is fixed by changing that section to

```
var permalink = '';
if ((post.find('.permalink').length <= 0 && post.find(".post_permalink").length <= 0) && (post.find(".post-info-tumblelog").find("a").length <= 0)) {
	return;
}
permalink = post.find(".permalink").attr('href');
if (!permalink) {
	permalink = post.find(".post-info-tumblelog").find("a").attr("href");
}
```

It also fails because of another nonexistent class:

```
if (XKit.extensions.timestamps.in_search && !$("#search_posts").hasClass("posts_view_list")) {
	var in_search_html = '<div class="xkit_timestamp_' + post_id + ' xtimestamp-in-search xtimestamp_loading">&nbsp;</div>';
	post.find(".post_controls_top").prepend(in_search_html);
} else {
```

`post_controls_top` does not exist in search page. This can probably be replaced with some other class that does exist. (For testing I went with `post_header` but I doubt that's optimal)

Finally, it uses custom `xtimestamp-in-search` style that uses absolute position to ensure text is placed where it cannot be seen.

Instead using
`XKit.tools.add_css('.xtimestamp-in-search { position: absolute; top: -6px; color: black; font-size: 12px; left: 60px; }', "timestamps_search");`
ensures text can be seen but it is not by any means in a proper position.

Very messy changed file is here: https://pastebin.com/rQ6xGpcE but it's not appropriate for merging and I don't think I have the skill necessary to improve it. edit: This file will make the sidebar very ugly in search page.

### PR DESCRIPTION
**Pull request by hobinjk**
Using @akunohomu's work in #1342 fix the display of timestamps in the
search view.

search

Closes #1342

### CODE REVIEW

File: Extensions/timestamps.js [hunk 1]
```diff
@@ -149,11 +155,16 @@ XKit.extensions.timestamps = new Object({
 
 			var blog_name = '';
 			if (XKit.interface.where().inbox !== true) {
-				if (post.find('.permalink').length <= 0 && post.find(".post_permalink").length <= 0) {
+				var permalink = '';
+				if ((post.find('.permalink').length <= 0 && post.find(".post_permalink").length <= 0) && (post.find(".post-info-tumblelog").find("a").length <= 0)) {
```
Comment (nightpool) [inline Extensions/timestamps.js]: should be `post.find('.permalink, .post_permalink, .post-info-tumblelog a')` and we should store the result to use below

File: Extensions/timestamps.js [hunk 2]
```diff
@@ -149,11 +155,16 @@ XKit.extensions.timestamps = new Object({
...
 					return;
 				}
+				permalink = post.find(".permalink").attr('href');
+				if (!permalink) {
+					permalink = post.find(".post-info-tumblelog").find("a").attr("href");
```
Comment (nightpool) [inline Extensions/timestamps.js]: should be replaced by attr('href') on the result of the above query

File: Extensions/timestamps.js [hunk 3]
```diff
@@ -149,11 +155,16 @@ XKit.extensions.timestamps = new Object({
...
+				}
+
 
-				var permalink = post.find(".permalink").attr('href');
 				if (post.find(".post_permalink").length > 0) {
 					permalink = post.find(".post_permalink").attr('href');
```
Comment (nightpool) [inline Extensions/timestamps.js]: see above

File: Extensions/timestamps.js [hunk 4]
```diff
@@ -172,7 +183,7 @@ XKit.extensions.timestamps = new Object({
 
 			if (XKit.extensions.timestamps.in_search && !$("#search_posts").hasClass("posts_view_list")) {
 				var in_search_html = '<div class="xkit_timestamp_' + post_id + ' xtimestamp-in-search xtimestamp_loading">&nbsp;</div>';
-				post.find(".post_controls_top").prepend(in_search_html);
+				post.find(".post-info-tumblelogs").prepend(in_search_html);
```
Comment (nightpool) [inline Extensions/timestamps.js]: if you're adding things to the brick layout, you also need to call `XKit.interface.trigger_reflow()` (which is debounced, so should be fine to call naively in a loop)

File: Extensions/timestamps.js (hunk 1 above)
Comment (hobinjk) [inline Extensions/timestamps.js]: :+1: Good point

File: Extensions/timestamps.js (hunk 4 above)
Comment (hobinjk) [inline Extensions/timestamps.js]: The added text is absolutely positioned so it doesn't change the size of the post card
