### PR TITLE
Merge #1044

### LINKED ISSUE #1207: Quick Tags breaks video posts
- Create a Youtube video post by pasting a url
- Add a tag or tags using the Quick Tags extension
- Note that the video is replaced with a "Watch on url.tumblr.com >" link

Probably related: when I make a video post with no caption, Quick Tags fails completely, returning Unable to edit post, error code QT01A200, Post cannot be empty.

Behavior is consistent whether or not the original post included tags.

(I haven't really looked around in your codebase, but I'm guessing the video portion of the post content is ignored when generating the edit content to post back with the API, so a post with no caption is treated as an empty post. Probably an easy fix depending on whether Tumblr's API is garbage and makes this difficult for some reason?)

### PR DESCRIPTION
**Pull request by nightpool**
Merge https://github.com/new-xkit/XKit/pull/1044 with conflicts fixed.

Fixes #1207

> Made it so XKit send post[one] when there's content to be sent.

### CODE REVIEW

File: Extensions/xkit_patches.js [hunk 1]
```diff
@@ -1859,8 +1859,8 @@ XKit.tools.getParameterByName = function(name){
 				m_return.is_mine = $(obj).hasClass("is_mine");
 				m_return.is_following = ($(obj).attr('data-following-tumblelog') === true);
 				m_return.can_edit = $(obj).find(".post_control.edit").length > 0;
-				
-				
+
```
Comment (nightpool) [inline Extensions/xkit_patches.js]: oops, guess editing it in sublime fixed some whitespace errors :P

**Comment by blackjackkent** [comment]
lgtm
@homu r+
