### PR TITLE
interface.kitty.get: retry with new form key upon initial failure

### LINKED ISSUE #1808: interface.kitty.get assumes form key is good/recent
We're still seeing kitty requests failing because `async_form_key` is only called [if there's no form key stored by XKit at all](https://github.com/new-xkit/XKit/pull/1787/files#diff-f3c602f5caa159014c2f7557700de10cR781) - and not, for example, if the form key is out of date due to logging out since the last form key storage.

since `XKit.storage` is defined in the bridge and isn't affected by XKit Patches, it should be safe to simply set `last_stored_form_key` to an empty string when XKit Main bails out of a login page, rather than fetching the form key every time we need it on a React page.

### PR DESCRIPTION
**Pull request by AprilSylph**
fixes #1808 
replaces, closes #1810 

adds a `retry_mode` argument to `XKit.interface.kitty.get`, which if true, forces `async_form_key` to be called.

### CODE REVIEW

File: Extensions/xkit_patches.js [hunk 1]
```diff
@@ -828,48 +828,39 @@ XKit.extensions.xkit_patches = new Object({
...
 					if (kitty_diff <= XKit.interface.kitty.expire_time && kitty_diff > 0) {
-						m_object.kitten = XKit.interface.kitty.stored;
-						callback(m_object);
+						callback({errors: false, kitten: XKit.interface.kitty.stored});
 						return;
 					}
 				}
 
-				if (!XKit.interface.form_key()) {
+				if (!XKit.interface.form_key() || retry_mode) {
```
Comment (nightpool) [inline Extensions/xkit_patches.js:843]: instead of using retry_mode here, maybe we could just invalidate `form_key` below, where we invalidate kitty.stored?

Comment (AprilSylph) [reply Extensions/xkit_patches.js:843]: we'd need to keep `retry_mode` as an argument to prevent actual failures from retrying infinitely, but yes
